# Generated by Django 5.2 on 2025-04-29 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_vote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('engineer', 'Engineer'), ('team_leader', 'Team Leader'), ('dep_leader', 'Department Leader'), ('manager', 'Senior Manager'), ('admin', 'Administrator')], max_length=20)),
                ('full_name', models.CharField(max_length=100)),
                ('team_id', models.IntegerField(blank=True, null=True)),
                ('dept_id', models.IntegerField(blank=True, null=True)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
